name: build-stan-windows-exe

on:
  workflow_dispatch:
  push:
    paths:
      - "model/**.stan"
      - "scripts/build.R"
      - ".github/workflows/build-stan.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 R + 把 Rtools43 放进 PATH（用 RSPM 提供二进制更稳）
      - name: Setup R (with Rtools)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          rtools-version: '43'
          windows-path-include-rtools: true
          use-public-rspm: true

      # 安装 remotes，并优先用 CRAN 安装 cmdstanr；失败则退到 GitHub
      - name: Install cmdstanr (CRAN first, GitHub fallback)
        run: |
          Rscript -e "options(repos=c(CRAN='https://cloud.r-project.org')); install.packages('remotes', quiet=TRUE)"
          Rscript -e "ok <- tryCatch({install.packages('cmdstanr', quiet=TRUE); TRUE}, error=function(e) FALSE); \
                      if (!ok || !requireNamespace('cmdstanr', quietly=TRUE)) { \
                        remotes::install_github('stan-dev/cmdstanr', upgrade='never'); \
                      } \
                      print(packageVersion('cmdstanr')); sessionInfo()"

      # （可选）缓存 CmdStan 编译目录，使二次构建更快
      - name: Cache CmdStan
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.cmdstanr
          key: cmdstan-${{ runner.os }}-43

      - name: Show toolchain
        shell: bash
        run: |
          echo "RTOOLS43_HOME=${RTOOLS43_HOME}"
          ls -l "$RTOOLS43_HOME/ucrt64/bin" || true

      - name: Build Stan EXE
        run: Rscript scripts/build.R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stan_windows_bundle
          path: stan_windows_bundle.zip
